### ISSUE TITLE
建立 GitHub Actions Docker 映像檔建置與發布 Workflow

### ISSUE THREAD

**Issue by jim60105** [jim60105/standalone-civitai-shortcut#25]
# 建立 GitHub Actions Docker 映像檔建置與發布 Workflow

## 目標
為 Civitai Shortcut 專案建立自動化的 Docker 映像檔建置與發布流程，參考 [`jim60105/docker-infinite-image-browsing`](https://github.com/jim60105/docker-infinite-image-browsing) 專案的 workflow 配置，實現完整的 CI/CD 流程。

## 背景
目前專案已具備 Dockerfile 用於建置 standalone 版本的 Docker 映像檔，但缺乏自動化的建置與發布流程。需要建立 GitHub Actions workflow 來自動建置多平台映像檔，並發布到容器映像倉庫。

#### 1. 建立可重用的 Docker 設置動作 (`.github/workflows/docker-reused-setup-steps/action.yml`)

建立一個可重用的 composite action 來處理 Docker 相關的設置：

```yaml
name: Setup docker
description: Configure the docker workflow.

inputs:
  DOCKERHUB_USERNAME:
    required: true
  DOCKERHUB_TOKEN:
    required: true
  QUAY_USERNAME:
    required: true
  QUAY_TOKEN:
    required: true
  tag:
    required: true
  CR_PAT:
    required: true

outputs:
  tags:
    description: "tags"
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: "labels"
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: composite
  steps:
    - name: Docker meta:${{ inputs.tag }}
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.DOCKERHUB_USERNAME }}/standalone-civitai-shortcut,ghcr.io/${{ github.repository_owner }}/standalone-civitai-shortcut,quay.io/${{ github.repository_owner }}/standalone-civitai-shortcut
        flavor: |
          latest=${{ inputs.tag == 'master' }}
        tags: |
          ${{ inputs.tag }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Create a Access Token and save it as as Actions secret
    # https://hub.docker.com/settings/security
    # DOCKERHUB_USERNAME
    # DOCKERHUB_TOKEN
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_TOKEN }}

    # You may need to manage write and read access of GitHub Actions for repositories in the container settings.
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.CR_PAT }}

    - name: Login to Quay Container Registry
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ inputs.QUAY_USERNAME }}
        password: ${{ inputs.QUAY_TOKEN }}
```

#### 2. 建立主要建置 Workflow (`.github/workflows/docker_publish.yml`)

```yaml
name: docker_publish

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  schedule:
    - cron: "0 5 1 * *" # 1st day of month at 5am UTC
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup docker
        id: setup
        uses: ./.github/workflows/docker-reused-setup-steps
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
          tag: ${{ github.ref_name }}
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: final
          tags: ${{ steps.setup.outputs.tags }}
          labels: ${{ steps.setup.outputs.labels }}
          build-args: |
            VERSION=${{ github.ref_name }}
            RELEASE=${{ github.run_number }}
          platforms: linux/amd64,linux/arm64
          # Cache to registry instead of gha to avoid the capacity limit.
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/standalone-civitai-shortcut:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/standalone-civitai-shortcut:cache,mode=max
          sbom: true
          provenance: true
```

#### 3. 建立安全掃描 Workflow (`.github/workflows/scan.yml`)

```yaml
name: scan

on:
  workflow_run:
    workflows: [docker_publish]
    types: [completed]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scan:
    name: Scan docker image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows/scan/html.tpl
          sparse-checkout-cone-mode: false

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/standalone-civitai-shortcut:latest"
          vuln-type: "os,library"
          scanners: vuln
          severity: "CRITICAL,HIGH"
          format: "template"
          template: "@.github/workflows/scan/html.tpl"
          output: "trivy-results.html"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results-*
          retention-days: 90
```

#### 4. 建立 Trivy 掃描結果 HTML 模板 (`.github/workflows/scan/html.tpl`)

```html
<!-- Template from
https://github.com/aquasecurity/trivy/blob/main/contrib/html.tpl -->
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
{{- if . }}
    <style>
      * {
        font-family: Arial, Helvetica, sans-serif;
      }
      h1 {
        text-align: center;
      }
      .group-header th {
        font-size: 200%;
      }
      .sub-header th {
        font-size: 150%;
      }
      table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        white-space: nowrap;
        padding: .3em;
      }
      table {
        margin: 0 auto;
      }
      .severity {
        text-align: center;
        font-weight: bold;
        color: #fafafa;
      }
      .severity-LOW .severity { background-color: #5fbb31; }
      .severity-MEDIUM .severity { background-color: #e9c600; }
      .severity-HIGH .severity { background-color: #ff8800; }
      .severity-CRITICAL .severity { background-color: #e40000; }
      .severity-UNKNOWN .severity { background-color: #747474; }
      .severity-LOW { background-color: #5fbb3160; }
      .severity-MEDIUM { background-color: #e9c60060; }
      .severity-HIGH { background-color: #ff880060; }
      .severity-CRITICAL { background-color: #e4000060; }
      .severity-UNKNOWN { background-color: #74747460; }
      table tr td:first-of-type {
        font-weight: bold;
      }
      .links a,
      .links[data-more-links=on] a {
        display: block;
      }
      .links[data-more-links=off] a:nth-of-type(1n+5) {
        display: none;
      }
      a.toggle-more-links { cursor: pointer; }
    </style>
    <title>{{- escapeXML ( index . 0 ).Target }} - Trivy Report - {{ now }} </title>
    <script>
      window.onload = function() {
        document.querySelectorAll('td.links').forEach(function(linkCell) {
          var links = [].concat.apply([], linkCell.querySelectorAll('a'));
          [].sort.apply(links, function(a, b) {
            return a.href > b.href ? 1 : -1;
          });
          links.forEach(function(link, idx) {
            if (links.length > 3 && 3 === idx) {
              var toggleLink = document.createElement('a');
              toggleLink.innerText = "Toggle more links";
              toggleLink.href = "#toggleMore";
              toggleLink.setAttribute("class", "toggle-more-links");
              linkCell.appendChild(toggleLink);
            }
            linkCell.appendChild(link);
          });
        });
        document.querySelectorAll('a.toggle-more-links').forEach(function(toggleLink) {
          toggleLink.onclick = function() {
            var expanded = toggleLink.parentElement.getAttribute("data-more-links");
            toggleLink.parentElement.setAttribute("data-more-links", "on" === expanded ? "off" : "on");
            return false;
          };
        });
      };
    </script>
  </head>
  <body>
    <h1>{{- escapeXML ( index . 0 ).Target }} - Trivy Report - {{ now }}</h1>
    <table>
    {{- range . }}
      <tr class="group-header"><th colspan="6">{{ .Type | toString | escapeXML }}</th></tr>
      {{- if (eq (len .Vulnerabilities) 0) }}
      <tr><th colspan="6">No Vulnerabilities found</th></tr>
      {{- else }}
      <tr class="sub-header">
        <th>Package</th>
        <th>Vulnerability ID</th>
        <th>Severity</th>
        <th>Installed Version</th>
        <th>Fixed Version</th>
        <th>Links</th>
      </tr>
        {{- range .Vulnerabilities }}
      <tr class="severity-{{ escapeXML .Vulnerability.Severity }}">
        <td class="pkg-name">{{ escapeXML .PkgName }}</td>
        <td>{{ escapeXML .VulnerabilityID }}</td>
        <td class="severity">{{ escapeXML .Vulnerability.Severity }}</td>
        <td class="pkg-version">{{ escapeXML .InstalledVersion }}</td>
        <td>{{ escapeXML .FixedVersion }}</td>
        <td class="links" data-more-links="off">
          {{- range .Vulnerability.References }}
          <a href={{ escapeXML . | printf "%q" }}>{{ escapeXML . }}</a>
          {{- end }}
        </td>
      </tr>
        {{- end }}
      {{- end }}
      {{- if (eq (len .Misconfigurations ) 0) }}
      <tr><th colspan="6">No Misconfigurations found</th></tr>
      {{- else }}
      <tr class="sub-header">
        <th>Type</th>
        <th>Misconf ID</th>
        <th>Check</th>
        <th>Severity</th>
        <th>Message</th>
      </tr>
        {{- range .Misconfigurations }}
      <tr class="severity-{{ escapeXML .Severity }}">
        <td class="misconf-type">{{ escapeXML .Type }}</td>
        <td>{{ escapeXML .ID }}</td>
        <td class="misconf-check">{{ escapeXML .Title }}</td>
        <td class="severity">{{ escapeXML .Severity }}</td>
        <td class="link" data-more-links="off"  style="white-space:normal;">
          {{ escapeXML .Message }}
          <br>
            <a href={{ escapeXML .PrimaryURL | printf "%q" }}>{{ escapeXML .PrimaryURL }}</a>
          </br>
        </td>
      </tr>
        {{- end }}
      {{- end }}
    {{- end }}
    </table>
{{- else }}
  </head>
  <body>
    <h1>Trivy Returned Empty Report</h1>
{{- end }}
  </body>
</html>
```

### 建置配置
- **觸發條件**：
  - `push` 到 `master` 分支
  - Git tag 推送（版本發布）
  - 手動觸發 (`workflow_dispatch`)
  - 定期建置（每月 1 日凌晨 5 點）

- **多平台支援**：
  - `linux/amd64`
  - `linux/arm64`

- **映像倉庫**：
  - Docker Hub: `{DOCKERHUB_USERNAME}/standalone-civitai-shortcut`
  - GitHub Container Registry: `ghcr.io/{repository_owner}/standalone-civitai-shortcut`
  - Quay.io: `quay.io/{repository_owner}/standalone-civitai-shortcut`

### 標籤策略
- `latest`：最新的 master 分支建置
- `{branch_name}`：分支名稱標籤
- `v{version}`：正式版本（根據 Git tag）

### 建置優化
- **Registry Cache**：使用 GitHub Container Registry 作為建置快取後端
- **多階段建置**：利用現有的 Nuitka 編譯階段
- **SBOM & Provenance**：生成軟體清單和來源證明

### 安全掃描
- **Trivy 漏洞掃描**：掃描 OS 和函式庫漏洞
- **嚴重性過濾**：只報告 CRITICAL 和 HIGH 等級漏洞
- **HTML 報告**：生成可讀性高的 HTML 格式掃描報告
- **工件上傳**：將掃描結果保存 90 天

## 必要的 GitHub Secrets

在 GitHub 專案設定中需要新增以下 secrets：

1. **Docker Hub**：
   - `DOCKERHUB_USERNAME`：Docker Hub 使用者名稱
   - `DOCKERHUB_TOKEN`：Docker Hub Access Token

2. **Quay.io**：
   - `QUAY_USERNAME`：Quay.io 使用者名稱
   - `QUAY_TOKEN`：Quay.io 存取令牌

3. **GitHub Token**：
   - `GITHUB_TOKEN`：GitHub 自動提供的內建 token（用於 GHCR）

## 檔案結構

實作完成後的檔案結構：

```
.github/workflows/
├── docker_publish.yml                 # 主要建置與發布 workflow
├── scan.yml                          # 安全掃描 workflow
├── test.yml                          # 現有測試 workflow (保持)
├── docker-reused-setup-steps/
│   └── action.yml                    # 可重用的 Docker 設置動作
└── scan/
    └── html.tpl                      # Trivy HTML 報告模板
```

### 步驟 1：建立目錄結構
```bash
mkdir -p .github/workflows/docker-reused-setup-steps
mkdir -p .github/workflows/scan
```

### 步驟 2：建立可重用動作檔案
建立 `.github/workflows/docker-reused-setup-steps/action.yml`

### 步驟 3：建立主要建置 workflow
建立 `.github/workflows/docker_publish.yml`

### 步驟 4：建立安全掃描 workflow
建立 `.github/workflows/scan.yml`

### 步驟 5：建立 HTML 模板
建立 `.github/workflows/scan/html.tpl`

### 步驟 6：設定 GitHub Secrets
在 GitHub 專案設定中新增必要的 secrets

### 步驟 7：測試 workflow
- 建立測試分支進行初步驗證
- 確認建置過程正常運作
- 驗證多平台建置功能
- 測試安全掃描功能

## 預期效益

1. **自動化發布**：每次版本更新自動建置並發布新的映像檔
2. **多平台支援**：支援 AMD64 和 ARM64 架構
3. **安全保障**：定期安全掃描確保映像檔安全性
4. **部署簡化**：使用者可直接使用預建的映像檔
5. **版本管理**：清晰的版本標籤管理
6. **效能優化**：使用 registry cache 加速建置

## 參考資料

- 參考專案：https://github.com/jim60105/docker-infinite-image-browsing
- Docker Buildx：https://docs.docker.com/buildx/
- GitHub Actions：https://docs.github.com/en/actions
- GitHub Container Registry：https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
- Trivy 安全掃描：https://github.com/aquasecurity/trivy

---

此實作計劃將為 Civitai Shortcut 專案建立完整的 Docker CI/CD 流程，提供安全、高效的容器化解決方案。

**Comment by jim60105** [comment]
## 📋 完整的 Workflow 配置範例

基於 `jim60105/docker-infinite-image-browsing` 專案的分析，以下是完整的 workflow 配置範例：

### 1. 主要建置與發布 Workflow

**檔案位置**: `.github/workflows/docker-build.yml`

```yaml
name: Docker Build and Publish

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # 每週日 UTC 2:00 建置 (避開尖峰時段)
    - cron: '0 2 * * 0'

env:
  REGISTRY_GHCR: ghcr.io
  REGISTRY_QUAY: quay.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # 用於 Trivy 安全掃描報告
      security-events: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      
      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Log in to Quay.io (optional)
        if: github.event_name != 'pull_request' && vars.QUAY_ENABLED == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_QUAY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY_QUAY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for master branch
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=edge,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-
          labels: |
            org.opencontainers.image.title=Civitai Shortcut
            org.opencontainers.image.description=Civitai Shortcut - A powerful tool for managing Civitai models and resources
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.documentation=${{ github.server_url }}/${{ github.repository }}/blob/master/README.md
            org.opencontainers.image.licenses=AGPL-3.0-or-later
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            RELEASE=${{ github.run_number }}
      
      - name: Generate SBOM
        if: github.event_name != 'pull_request'
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          format: spdx-json
          output-file: sbom.spdx.json
      
      - name: Upload SBOM
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
      
      - name: Run Trivy vulnerability scanner
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results to GitHub Security tab
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
```

### 2. 安全掃描 Workflow

**檔案位置**: `.github/workflows/scan.yml`

```yaml
name: Security Scan

on:
  schedule:
    # 每日 UTC 6:00 執行安全掃描
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to scan (default: latest)'
        required: false
        default: 'latest'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag || 'latest' }}
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
      
      - name: Run Trivy vulnerability scanner (JSON output)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag || 'latest' }}
          format: 'json'
          output: 'trivy-results.json'
      
      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: |
            trivy-results.sarif
            trivy-results.json
  
  dockerfile-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Hadolint Dockerfile Linter
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true
      
      - name: Upload Hadolint scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-results.sarif
```

### 3. 映像檔測試 Workflow

**檔案位置**: `.github/workflows/test-image.yml`

```yaml
name: Test Docker Image

on:
  workflow_run:
    workflows: ["Docker Build and Publish"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to test (default: latest)'
        required: false
        default: 'latest'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Test image startup
        run: |
          IMAGE_TAG="${{ github.event.inputs.image_tag || 'latest' }}"
          PLATFORM="${{ matrix.platform }}"
          
          echo "Testing image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} on ${PLATFORM}"
          
          # 創建測試用的暫存目錄
          mkdir -p test_outputs
          
          # 運行容器並測試基本功能
          docker run --rm \
            --platform ${PLATFORM} \
            -v $(pwd)/test_outputs:/outputs \
            -p 8080:8080 \
            -d \
            --name civitai-test \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}
          
          # 等待容器啟動
          sleep 10
          
          # 檢查容器是否正在運行
          if docker ps | grep civitai-test; then
            echo "✅ Container started successfully"
          else
            echo "❌ Container failed to start"
            docker logs civitai-test
            exit 1
          fi
          
          # 檢查健康狀態 (如果應用支援)
          # curl -f http://localhost:8080/health || echo "Health check endpoint not available"
          
          # 清理
          docker stop civitai-test || true
          docker rm civitai-test || true
      
      - name: Test image security
        run: |
          IMAGE_TAG="${{ github.event.inputs.image_tag || 'latest' }}"
          PLATFORM="${{ matrix.platform }}"
          
          # 檢查映像檔是否以非 root 用戶運行
          USER_ID=$(docker run --rm --platform ${PLATFORM} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} id -u)
          if [ "$USER_ID" = "0" ]; then
            echo "❌ Container runs as root user"
            exit 1
          else
            echo "✅ Container runs as non-root user (UID: $USER_ID)"
          fi
```

### 4. 清理舊映像檔 Workflow

**檔案位置**: `.github/workflows/cleanup.yml`

```yaml
name: Cleanup Old Images

on:
  schedule:
    # 每月第一天清理舊映像檔
    - cron: '0 3 1 * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: true
```

### 5. 通知 Workflow

**檔案位置**: `.github/workflows/notify.yml`

```yaml
name: Build Notifications

on:
  workflow_run:
    workflows: ["Docker Build and Publish"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.ref == 'refs/heads/master' }}
    
    steps:
      - name: Create Issue on Build Failure
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 Docker Build Failed - ${new Date().toISOString().split('T')[0]}`,
              body: `## Build Failure Report
              
              **Workflow Run**: ${context.payload.workflow_run.html_url}
              **Commit**: ${context.payload.workflow_run.head_commit.id}
              **Branch**: ${context.payload.workflow_run.head_branch}
              **Author**: ${context.payload.workflow_run.head_commit.author.name}
              
              Please investigate the build failure and fix the issues.
              
              ---
              Auto-generated by GitHub Actions`,
              labels: ['bug', 'ci/cd', 'high-priority']
            })
```

## 🔧 配置說明

### 必要的 Secrets 設定

在 GitHub repository 的 Settings > Secrets and variables > Actions 中設定：

- `GITHUB_TOKEN` - 自動提供，用於 GHCR
- `QUAY_USERNAME` - Quay.io 用戶名 (選用)
- `QUAY_PASSWORD` - Quay.io 密碼 (選用)

### 必要的 Variables 設定

在 Settings > Secrets and variables > Actions > Variables 中設定：

- `QUAY_ENABLED` - 設為 `true` 啟用 Quay.io 發布

### 功能特色

1. **多平台支援**: 支援 AMD64 和 ARM64 架構
2. **多倉庫發布**: 支援 GitHub Container Registry 和 Quay.io
3. **智能標籤**: 根據分支、PR、版本自動產生標籤
4. **安全掃描**: 整合 Trivy 和 Hadolint 進行安全掃描
5. **映像檔測試**: 自動測試映像檔啟動和安全性
6. **自動清理**: 定期清理舊版本映像檔
7. **失敗通知**: 建置失敗時自動建立 issue

這套 workflow 配置完全參考了 `jim60105/docker-infinite-image-browsing` 的最佳實踐，並針對 Civitai Shortcut 專案進行了適當的調整。
