### ISSUE TITLE
改進 Docker 多平台建置：實現分散式建置以提升 CI/CD 效能

### ISSUE THREAD

**Issue by jim60105** [jim60105/standalone-civitai-shortcut#29]
# 改進 Docker 多平台建置：實現分散式建置以提升 CI/CD 效能

## 問題描述

目前我們的 `docker_publish.yml` 工作流程在單一 `ubuntu-latest` runner 上同時建置 `linux/amd64` 和 `linux/arm64` 兩個平台的映像檔。這種方式有以下問題：

1. **ARM64 模擬建置效能低落**：在 x86 runner 上透過 QEMU 模擬 ARM64 建置極為緩慢
2. **建置時間過長**：所有平台的建置都必須依序完成，無法並行處理
3. **資源使用效率低**：無法充分利用 GitHub Actions 的並行處理能力

## 解決方案概述

根據 [Docker 官方文件](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners)，我們將實現分散式建置架構：

1. **分離建置階段**：使用 matrix strategy 為每個平台分配獨立的 runner
2. **合併階段**：建立 manifest list 整合所有平台的映像檔
3. **保留現有功能**：維持多註冊表推送、attestation 等現有功能

#### 1.1 建立建置矩陣 Job (`build`)
- 使用 `matrix.platform` 為 `linux/amd64` 和 `linux/arm64` 建立並行 job
- 每個平台在獨立的 runner 上建置
- 使用 `push-by-digest=true` 推送 digest 而非標籤
- 將建置產生的 digest 上傳為 artifact

**涉及步驟：**
```yaml
strategy:
  fail-fast: false
  matrix:
    platform:
      - linux/amd64
      - linux/arm64
```

#### 1.2 重構現有設定步驟
- 保留現有的 `docker-reused-setup-steps` 設定
- 確保每個建置 job 都能正確設定 Docker registry 認證
- 維持現有的建置參數 (`VERSION`, `RELEASE`)

#### 1.3 實作 Digest 管理
- 為每個平台建立唯一的 artifact 名稱：`digests-${PLATFORM_PAIR}`
- 匯出建置 digest 到臨時檔案
- 上傳 digest artifact 供後續合併使用

#### 2.1 建立合併 Job
- 依賴所有建置 job 完成
- 下載所有平台的 digest artifacts
- 使用 `docker buildx imagetools create` 建立 manifest list

#### 2.2 多註冊表支援
- 維持對 Docker Hub、GHCR、Quay.io 的推送支援
- 確保所有註冊表都能正確建立 manifest list
- 保留現有的標籤策略 (branches, tags, schedule)

#### 2.3 Attestation 支援
- 在合併階段完成後執行 attestation
- 為每個註冊表建立 build provenance
- 維持現有的 SBOM 和 provenance 功能

#### 3.1 快取策略優化
- 確保分散式建置能有效利用 registry cache
- 維持現有的 cache-from/cache-to 設定
- 避免 cache 衝突問題

#### 3.2 錯誤處理改進
- 實作 `fail-fast: false` 確保部分平台失敗不影響其他平台
- 新增建置狀態檢查與報告
- 改進錯誤訊息與除錯資訊

#### 3.3 效能監控
- 新增建置時間測量
- 比較新舊架構的效能差異
- 建立效能基準測試

### 步驟 1：準備工作環境設定
```bash
# 確認當前工作流程狀態
git status
git checkout master  # 確保從最新的 master 分支開始

# 建立功能分支
git checkout -b feature/distributed-docker-build
```

#### 2.1 新增環境變數
在工作流程檔案頂層新增：
```yaml
env:
  REGISTRY_IMAGE: ${{ github.repository_owner }}/standalone-civitai-shortcut
```

#### 2.2 重構為三個 Job

**Job 1: `prepare` (可選，用於動態設定)**
- 如果需要動態決定建置平台，可加入此 job
- 目前可先省略，直接使用固定的平台矩陣

**Job 2: `build`**
```yaml
build:
  runs-on: ubuntu-latest
  strategy:
    fail-fast: false
    matrix:
      platform:
        - linux/amd64
        - linux/arm64
  steps:
    - name: Prepare platform variables
      run: |
        platform=${{ matrix.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
    
    # ... 其他步驟
```

**Job 3: `merge`**
```yaml
merge:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        path: /tmp/digests
        pattern: digests-*
        merge-multiple: true
    
    # ... 合併邏輯
```

#### 3.1 修改建置步驟
將現有的 `Build and push` 步驟修改為：
```yaml
- name: Build and push by digest
  id: build
  uses: docker/build-push-action@v6
  with:
    context: .
    file: ./Dockerfile
    push: true
    target: final
    platforms: ${{ matrix.platform }}
    labels: ${{ steps.setup.outputs.labels }}
    build-args: |
      VERSION=${{ github.ref_name }}
      RELEASE=${{ github.run_number }}
    cache-from: |
      type=registry,ref=ghcr.io/${{ github.repository_owner }}/standalone-civitai-shortcut:cache
    cache-to: |
      type=registry,ref=ghcr.io/${{ github.repository_owner }}/standalone-civitai-shortcut:cache,mode=max
    outputs: type=image,push-by-digest=true,name-canonical=true,push=true
    sbom: true
    provenance: true
```

#### 3.2 實作 Digest 匯出
```yaml
- name: Export digest
  run: |
    mkdir -p /tmp/digests
    digest="${{ steps.build.outputs.digest }}"
    touch "/tmp/digests/${digest#sha256:}"

- name: Upload digest
  uses: actions/upload-artifact@v4
  with:
    name: digests-${{ env.PLATFORM_PAIR }}
    path: /tmp/digests/*
    if-no-files-found: error
    retention-days: 1
```

#### 4.1 建立 manifest list
```yaml
- name: Create manifest list and push
  working-directory: /tmp/digests
  run: |
    # 為每個註冊表建立 manifest list
    for registry in ghcr.io/${{ github.repository_owner }} ${{ secrets.DOCKERHUB_USERNAME }} quay.io/${{ github.repository_owner }}; do
      # 建立標籤列表
      tags=$(echo "${{ steps.setup.outputs.tags }}" | grep "^${registry}/" | tr '\n' ' ')
      if [ -n "$tags" ]; then
        docker buildx imagetools create $tags \
          $(printf "${registry}/standalone-civitai-shortcut@sha256:%s " *)
      fi
    done
```

#### 4.2 保留 Attestation 功能
將現有的三個 attestation 步驟移至 `merge` job 的最後：
```yaml
- name: Attest GHCR image
  uses: actions/attest-build-provenance@v2
  with:
    subject-name: ghcr.io/${{ github.repository_owner }}/standalone-civitai-shortcut
    subject-digest: ${{ steps.get_digest.outputs.ghcr_digest }}
```

#### 5.1 本地測試準備
```bash
# 檢查 Dockerfile 語法
docker build --dry-run .

# 驗證工作流程語法
gh workflow view docker_publish.yml
```

#### 5.2 建立測試分支推送
```bash
git add .github/workflows/docker_publish.yml
git commit -s --author="🤖 GitHub Copilot <github-copilot[bot]@users.noreply.github.com>" \
  -m "feat: implement distributed multi-platform Docker build

- Split single-runner build into matrix strategy for parallel platform builds
- Implement digest-based build with manifest list creation
- Maintain existing multi-registry push and attestation features
- Improve build performance by eliminating ARM64 emulation overhead

Resolves #[ISSUE_NUMBER]"

git push origin feature/distributed-docker-build
```

#### 5.3 建立測試 PR
- 建立 Pull Request 觸發工作流程測試
- 監控建置時間與成功率
- 驗證所有註冊表的映像檔正確性

#### 6.1 效能比較
- 記錄改進前後的建置時間
- 比較資源使用效率
- 驗證映像檔功能性

#### 6.2 文件更新
- 更新 README 中的 CI/CD 說明
- 記錄新架構的運作原理
- 提供故障排除指南

### 效能改進
- **建置時間縮短**：預計減少 50-70% 的建置時間
- **並行處理**：兩個平台可同時建置，而非依序執行
- **原生建置**：消除 ARM64 模擬overhead

### 維護性提升
- **更清晰的責任分離**：建置與合併階段職責明確
- **更好的錯誤隔離**：單一平台失敗不影響其他平台
- **更易除錯**：每個平台的建置日誌獨立可見

### 兼容性保證
- **完全向後兼容**：維持所有現有功能
- **無破壞性變更**：最終產出的映像檔完全相同
- **無額外依賴**：使用現有的 GitHub Actions 功能

## 注意事項

1. **Artifact 存儲限制**：digest artifacts 僅保留 1 天，足夠工作流程使用
2. **網路依賴**：合併階段需要下載所有 digest artifacts
3. **標籤管理**：確保各註冊表的標籤格式正確處理
4. **快取共享**：驗證分散式建置的快取共享機制

## 驗收標準

- [ ] 工作流程能成功建置並推送多平台映像檔
- [ ] 建置時間較原架構顯著縮短
- [ ] 所有三個註冊表 (GHCR, Docker Hub, Quay) 都能正確推送
- [ ] Attestation 和 provenance 功能正常運作
- [ ] 快取機制有效運作
- [ ] 錯誤處理機制完善
- [ ] 文件更新完整

此改進將大幅提升我們的 CI/CD 流程效率，同時保持所有現有功能的完整性。
