### ISSUE TITLE
修復 Docker 多平台發布流程中的 push-by-digest 錯誤

### ISSUE THREAD

**Issue by jim60105** [jim60105/standalone-civitai-shortcut#31]
# 問題描述

Docker 發布流程在 merge 階段失敗，錯誤信息為：`ERROR: can't push with no tags specified, please set --tag or --dry-run`

## 錯誤分析

根據對錯誤日誌和相關 GitHub 討論的深入研究，問題的根本原因在於 `push-by-digest=true` 模式下的標籤配置錯誤。

### 核心問題

1. **標籤格式衝突**: 在使用 `push-by-digest=true` 時，`tags` 參數不應包含完整的標籤（如 `:latest`），而應該只包含 repository 名稱
2. **Merge 階段配置錯誤**: 在 `Create manifest list and push` 步驟中使用了錯誤的標籤格式
3. **缺失的 digest 引用**: 在 attest 步驟中引用了不存在的 `steps.build.outputs.digest`

### 參考文獻

- [GitHub 討論 #1213](https://github.com/docker/build-push-action/discussions/1213#discussioncomment-10414120): 明確指出當使用 `push-by-digest=true` 時，tags 應該是 repository 名稱，不應包含標籤
- [Docker 官方文檔](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners): 多平台構建的正確配置方式

### 1. 修正 Build 階段的標籤配置

**問題文件**: `.github/workflows/docker_publish.yml` (第 64 行)

**當前錯誤配置**:
```yaml
tags: ${{ secrets.DOCKERHUB_USERNAME }}/standalone-civitai-shortcut,ghcr.io/${{ env.REGISTRY_IMAGE }},quay.io/${{ env.REGISTRY_IMAGE }}
```

**正確配置**: 
由於使用了 `push-by-digest=true`，tags 應該只是 repository 名稱，不包含任何標籤。但實際上，根據 Docker 官方文檔，更好的做法是使用 `outputs` 中的 `name` 參數來指定 repository，而不是在 `tags` 中指定。

**建議修改**:
```yaml
# 移除 tags 參數，或只保留用於 metadata 的標籤
outputs: type=image,name=${{ secrets.DOCKERHUB_USERNAME }}/standalone-civitai-shortcut,push-by-digest=true,name-canonical=true,push=true
```

同時為其他 registry 添加額外的 outputs：
```yaml
outputs: |
  type=image,name=${{ secrets.DOCKERHUB_USERNAME }}/standalone-civitai-shortcut,push-by-digest=true,name-canonical=true,push=true
  type=image,name=ghcr.io/${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
  type=image,name=quay.io/${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
```

### 2. 修正 Merge 階段的標籤使用

**問題文件**: `.github/workflows/docker_publish.yml` (第 123-131 行)

**當前錯誤配置**:
```bash
tags=$(echo "${{ steps.setup.outputs.tags }}" | grep "^${registry}/" | tr '\n' ' ')
if [ -n "$tags" ]; then
  docker buildx imagetools create $tags $(printf "${registry}/standalone-civitai-shortcut@sha256:%s " "${digests[@]}")
fi
```

**正確配置**:
```bash
tags=$(echo "${{ steps.setup.outputs.tags }}" | grep "^${registry}/" | tr '\n' ' ')
if [ -n "$tags" ]; then
  docker buildx imagetools create $(echo "$tags" | sed 's/^/-t /') $(printf "${registry}/standalone-civitai-shortcut@sha256:%s " "${digests[@]}")
fi
```

注意: 需要為每個標籤添加 `-t` 前綴。

### 3. 修正 Attest 步驟的 Digest 引用

**問題文件**: `.github/workflows/docker_publish.yml` (第 134-147 行)

**當前錯誤配置**:
```yaml
subject-digest: ${{ steps.build.outputs.digest }}
```

**正確配置**:
Attest 步驟位於 merge job 中，但 `steps.build.outputs.digest` 來自 build job。需要通過 outputs 傳遞或在 merge 階段重新獲取 digest。

**建議方案 1 - 通過 job outputs 傳遞**:
在 build job 中添加：
```yaml
outputs:
  digest: ${{ steps.build.outputs.digest }}
```

在 merge job 中：
```yaml
needs: build
steps:
  # ... 其他步驟
  - name: Attest GHCR image
    uses: actions/attest-build-provenance@v2
    with:
      subject-name: ghcr.io/${{ github.repository_owner }}/standalone-civitai-shortcut
      subject-digest: ${{ needs.build.outputs.digest }}
```

**建議方案 2 - 在 merge 階段重新獲取**:
```bash
# 在 Create manifest list and push 步驟後添加
digest=$(docker buildx imagetools inspect ghcr.io/${{ github.repository_owner }}/standalone-civitai-shortcut:${{ github.ref_name }} --format "{{.Manifest.Digest}}")
echo "MANIFEST_DIGEST=$digest" >> $GITHUB_ENV
```

然後在 attest 步驟中使用：
```yaml
subject-digest: ${{ env.MANIFEST_DIGEST }}
```

### 4. 改進的完整解決方案

根據 Docker 官方文檔最佳實踐，建議採用以下結構：

**Build 階段**:
```yaml
- name: Build and push by digest
  id: build
  uses: docker/build-push-action@v6
  with:
    context: .
    file: ./Dockerfile
    target: final
    platforms: ${{ matrix.platform }}
    labels: ${{ steps.setup.outputs.labels }}
    build-args: |
      VERSION=${{ github.ref_name }}
      RELEASE=${{ github.run_number }}
    cache-from: |
      type=registry,ref=ghcr.io/${{ env.REGISTRY_IMAGE }}:cache
    cache-to: |
      type=registry,ref=ghcr.io/${{ env.REGISTRY_IMAGE }}:cache,mode=max
    outputs: |
      type=image,name=${{ secrets.DOCKERHUB_USERNAME }}/standalone-civitai-shortcut,push-by-digest=true,name-canonical=true,push=true
      type=image,name=ghcr.io/${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
      type=image,name=quay.io/${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
    sbom: true
    provenance: true
```

**Merge 階段**:
```bash
docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
  $(printf '${{ secrets.DOCKERHUB_USERNAME }}/standalone-civitai-shortcut@sha256:%s ' *)
```

## 實施步驟

1. **備份當前配置**: 確保在修改前有備份
2. **更新 build 階段**: 修正 tags 和 outputs 配置
3. **更新 merge 階段**: 修正 imagetools create 命令
4. **修正 attest 步驟**: 解決 digest 引用問題
5. **測試**: 在測試分支上驗證修復
6. **部署**: 合併到主分支

## 預期結果

修復後，Docker 多平台發布流程應該能夠：
1. 成功構建多平台映像
2. 正確推送 digest 到多個註冊表
3. 成功創建並推送 manifest list
4. 完成映像簽證證明

## 相關問題

這個修復將解決以下錯誤：
- `ERROR: can't push with no tags specified, please set --tag or --dry-run`
- Multi-platform image merge 失敗
- Attestation 步驟中的 digest 引用錯誤

## 技術債務

考慮在未來版本中：
1. 統一多個註冊表的配置管理
2. 改進錯誤處理和日誌記錄
3. 添加更多的測試覆蓋率
